-- introdução SQL
-- DLL - Linguagem de Definição de dados
CREATE DATABASE BD_INTRO;

USE BD_INTRO;

CREATE TABLE CLIENTE (
	NOME VARCHAR(60),
	CODIGO INT
);

ALTER TABLE CLIENTE ADD EMAIL VARCHAR(40);
ALTER TABLE CLIENTE ADD TESTE INT;
--DROP
DROP TABLE CLIENTE;

--REMOVER A COLUNA TESTE
ALTER TABLE CLIENTE DROP COLUMN TESTE;


---
CREATE DATABASE SISTEMA;
USE SISTEMA;

CREATE TABLE PESSOAS (
	PES_CODIGO INT NOT NULL PRIMARY KEY IDENTITY, --AUTO INCREMENTO
	PES_NOME VARCHAR(50) NOT NULL,
	PES_CPF VARCHAR(11) NOT NULL UNIQUE,
	PES_STATUS INT CHECK(PES_STATUS IN (1,2,3,4))
);

INSERT INTO PESSOAS VALUES ('BATMAN','1111111111',1);
INSERT INTO PESSOAS VALUES ('SPIDERMAN','2222222222',1);

SELECT * FROM PESSOAS


CREATE TABLE CLIENTES (
	CLI_CODIGO INT NOT NULL PRIMARY KEY,
	CLI_RENDA DECIMAL(8,2), --000000.00
	CLI_CREDITO DECIMAL(7,2),
	FOREIGN KEY (CLI_CODIGO) REFERENCES PESSOAS (PES_CODIGO)

);

SELECT * FROM CLIENTES

CREATE TABLE FUNCIONARIOS (
	FUN_CODIGO INT NOT NULL PRIMARY KEY,
	FUN_SALARIO DECIMAL(7,2) CHECK (FUN_SALARIO>0),
	FOREIGN KEY (FUN_CODIGO) REFERENCES PESSOAS (PES_CODIGO)
);

--IDENTITY: Controle de auto-incremento (inicia com o valor 1)
--NOT NULL: Define o campo como obrigatório
--UNIQUE: Garante que o valor não será repitido

CREATE TABLE PRODUTOS (
	PRD_CODIGO INT NOT NULL PRIMARY KEY IDENTITY,
	PRD_DESCICAO VARCHAR(60) NOT NULL,
	PRD_QTD INT,
	PRD_VALOR DECIMAL (7,2) CHECK(PRD_VALOR>0),
	PRD_STATUS INT CHECK (PRD_STATUS IN (1,2,3,4,5))
);

CREATE TABLE PEDIDOS (
	PED_NUMERO INT NOT NULL PRIMARY KEY IDENTITY,
	PED_DATA DATETIME, --DATE
	PED_VALOR DECIMAL(7,2),
	PED_STATUS INT NOT NULL CHECK (PED_STATUS IN (1,2,3,4,5)),
	FUN_CODIGO INT,
	CLI_CODIGO INT,
	FOREIGN KEY (FUN_CODIGO) REFERENCES FUNCIONARIOS (FUN_CODIGO),
	FOREIGN KEY (CLI_CODIGO) REFERENCES CLIENTES (CLI_CODIGO)
);

CREATE TABLE ITENS_PEDIDOS (
	PED_NUMERO INT NOT NULL,
	PRD_CODIGO INT NOT NULL,
	IP_QTD INT NOT NULL,
	IP_VALOR DECIMAL(7,2) NOT NULL,
	PRIMARY KEY (PED_NUMERO, PRD_CODIGO), --Chave-composta
	FOREIGN KEY (PED_NUMERO) REFERENCES PEDIDOS (PED_NUMERO),
	FOREIGN KEY (PRD_CODIGO) REFERENCES PRODUTOS (PRD_CODIGO)
	--FOREIGN KEY PED_NUMERO
	--FOREIGN KEY PRD_CODIGO
);

INSERT INTO PRODUTOS(PRD_DESCICAO, PRD_VALOR, PRD_QTD, PRD_STATUS)
VALUES ('LAPISEIRA MÁGICA', 13.99, 50, 1);

INSERT INTO PRODUTOS(PRD_DESCICAO, PRD_VALOR, PRD_QTD, PRD_STATUS)
VALUES ('APONTADOR', 5.69, 20, 2),
       ('CANETA AZUL', 14.98, 100, 1);

--CADASTRO MAIS 3 PRODUTOS

INSERT INTO PRODUTOS(PRD_DESCICAO, PRD_VALOR, PRD_QTD, PRD_STATUS)
VALUES ('AMACIANTE DOWNIE 700ML LAVANDA', 14.90, 2000, 1),
		('ARROZ PEDRETTI T1 5KG', 18.00, 4000, 1),
		('CERV BRAHMA DUPLO MALTE LT 350ML', 3.18, 3000, 1);

UPDATE PRODUTOS SET PRD_DESCICAO = 'LAPISEIRA' WHERE PRD_CODIGO = 1; 

SELECT * FROM PRODUTOS;

--SIMULAÇÃO
--1 TENTAR INSERIR UMA PESSOA COM UM CPF QUE JÁ EXISTE CADASTRADO (CÓDIGO + PRINT ERRO)
SELECT * FROM PESSOAS
INSERT INTO PESSOAS VALUES ('JOEL','1111111111', 1);

--2 TENTAR INSERIR NOVO PRODUTO COM CÓDIGO INVALIDO (CÓDIGO + PRINT)
INSERT INTO PRODUTOS VALUES ('FRALDA PAMPERS TAMNH G', 67.90, 0);

--3 CADASTRAR DOIS NOVO CLIENTES ULTILIZANDO PES_CODIGO EXISTENTE (CÓDIGO + PRINT)
SELECT * FROM PESSOAS

INSERT INTO CLIENTES VALUES (2, 1543.00, 0)
SELECT * FROM CLIENTES

--4 CADASTRAR UM NOVO FUNCIONARIO ULTILZANDO PES_CODIGO EXISTENTE (CÓDIGO + PRINT)
INSERT INTO PESSOAS VALUES ('JAILSON','77777777777',1);
SELECT * FROM PESSOAS
INSERT INTO FUNCIONARIOS VALUES (9, 1900.00)
SELECT * FROM FUNCIONARIOS

--5 CADASTRAR DOIS NOVOS PRODUTOS (CÓDIGO + PRINT)

INSERT INTO PRODUTOS(PRD_DESCICAO, PRD_VALOR, PRD_QTD, PRD_STATUS)
VALUES ('LEITE INT TP 1L BATAVO', 6.90, 220, 3),
		('CAFE 3 COR EXTRA FORTE', 36.00, 10, 1)
SELECT * FROM PRODUTOS

--6 ALTERAR PRD_VALOR DE UM PRODUTO (CÓDIGO + PRINT)

UPDATE PRODUTOS SET PRD_VALOR = 13.99 WHERE PRD_VALOR = 5.69; 
SELECT * FROM PRODUTOS

--7 CADASTRAR 3 NOVOS PEDIDOS (CADA PEDIDO TEM NO MINIMO 2 PRODUTOS VENDIDOS (CÓDIGO + PRINT)

INSERT INTO PEDIDOS VALUES (GETDATE(), 20.00, 1, 9, 7 )
INSERT INTO PEDIDOS VALUES (GETDATE(), 20.00, 1, 9, 2 )
INSERT INTO PEDIDOS VALUES (GETDATE(), 30.00, 1, 9, 7 )
SELECT * FROM PEDIDOS










---------------------------------------------1 EXERCICIOS DDL E DML-------------------------------------------------------

 CREATE DATABASE ESCOLA;
 USE ESCOLA;

 CREATE TABLE INSTRUTOR (
	INS_CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	INS_NOME VARCHAR(20) NOT NULL,
	FUN_SALARIO DECIMAL(10,2) CHECK (FUN_SALARIO>0)
);

CREATE TABLE CURSO (
	CUR_CODCURSO INT NOT NULL PRIMARY KEY,
	CUR_NOME VARCHAR(20) NOT NULL,
	CUR_PONTUACAO DECIMAL(4,2)

);

CREATE TABLE PARTICIPANTE ( 
	PAR_CPF VARCHAR(11) NOT NULL PRIMARY KEY,
	PAR_MATRICULA INT NOT NULL,
	PAR_NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TURMA (
	TUR_CODTURMA INT NOT NULL PRIMARY KEY,
	TUR_SALA INT NOT NULL,
	TUR_HORARIO DATETIME,
	TUR_CPFINSTRUTOR VARCHAR(11),
	TUR_CODCURSO INT,
	FOREIGN KEY (TUR_CODCURSO) REFERENCES CURSO (CUR_CODCURSO),
	FOREIGN KEY (TUR_CPFINSTRUTOR) REFERENCES INSTRUTOR (INS_CPF)
	
);

CREATE TABLE MATRICULA (
	PAR_CPF VARCHAR(11),
	TUR_CODTURMA INT,
	PRIMARY KEY (PAR_CPF, TUR_CODTURMA),
	FOREIGN KEY (PAR_CPF) REFERENCES PARTICIPANTE (PAR_CPF),
	FOREIGN KEY (TUR_CODTURMA) REFERENCES TURMA (TUR_CODTURMA)
);


---- 2

--- INSERT PARTICIPANTE
INSERT INTO PARTICIPANTE VALUES ('04640703090', 1, 'GLAUBER FAZOELE ALMEIDA');
INSERT INTO PARTICIPANTE VALUES ('04640503090', 2, 'ISADORA FAZOELE ALMEIDA');
INSERT INTO PARTICIPANTE VALUES ('04640203090', 3, 'JAO FAZOELE ALMEIDA');
INSERT INTO PARTICIPANTE VALUES ('66375090008', 4, 'JAIR ALMEIDA');
INSERT INTO PARTICIPANTE VALUES ('44944860005', 5, 'LULE ALMEIDA');
SELECT * FROM PARTICIPANTE

--- INSERT INSTRUTOR

INSERT INTO INSTRUTOR VALUES ('03523231332', 'REGINALDO PEREIRA', 1600.00)
INSERT INTO INSTRUTOR VALUES ('03502197032', 'GABI ARAUJO', 1600.00)
INSERT INTO INSTRUTOR VALUES ('17061752050', 'JOSE PEREIRA', 1600.00)
INSERT INTO INSTRUTOR VALUES ('42902229003', 'GABRIEL MAGALHAES', 1600.00)
INSERT INTO INSTRUTOR VALUES ('49041927026', 'BARBARA BARBOSA', 3400.00)
SELECT * FROM INSTRUTOR

--- INSERT CURSO
INSERT INTO CURSO VALUES (1, 'SISTEMAS', 40.00)
INSERT INTO CURSO VALUES (2, 'PSICOLOGIA', 70.00)
INSERT INTO CURSO VALUES (3, 'AGRO', 10.00)
INSERT INTO CURSO VALUES (4, 'ADMINSITRAÇÃO', 50.00)
INSERT INTO CURSO VALUES (5, 'DIREITO', 90.00)
SELECT * FROM CURSO

--- INSERT TURMA
INSERT INTO TURMA VALUES (1, 2, GETDATE(), '49041927026', 1)
INSERT INTO TURMA VALUES (2, 3, GETDATE(), '42902229003', 2)
INSERT INTO TURMA VALUES (4, 5, GETDATE(), '17061752050', 3)
INSERT INTO TURMA VALUES (6, 7, GETDATE(), '03502197032', 4)
INSERT INTO TURMA VALUES (8, 9, GETDATE(), '03523231332', 5)
SELECT * FROM TURMA

--- INSERT MATRICULA

SELECT * FROM TURMA
SELECT * FROM PARTICIPANTE

INSERT INTO MATRICULA VALUES ('04640703090', 1)
INSERT INTO MATRICULA VALUES ('66375090008', 2)
INSERT INTO MATRICULA VALUES ('04640503090', 6)
INSERT INTO MATRICULA VALUES ('44944860005', 4)
INSERT INTO MATRICULA VALUES ('04640203090', 8)
SELECT * FROM MATRICULA

----- ALTERANDO OS DADOS

UPDATE PARTICIPANTE SET PAR_CPF = '04640203090' WHERE PAR_MATRICULA = 3; 
SELECT * FROM PARTICIPANTE
UPDATE INSTRUTOR SET INS_NOME = 'LIPAO ALMDEIDA' WHERE INS_CPF = '03502197032';
SELECT * FROM INSTRUTOR
UPDATE CURSO SET CUR_PONTUACAO = 40.00 WHERE CUR_CODCURSO = 2;
SELECT * FROM CURSO
UPDATE PARTICIPANTE SET PAR_NOME = 'CLARICE SEMB OLAS' WHERE PAR_CPF = '66375090008';
SELECT * FROM PARTICIPANTE
UPDATE MATRICULA SET TUR_CODTURMA = 6 WHERE PAR_CPF = '04640203090';
SELECT * FROM MATRICULA


--- REMOVENDO DADOS DAS TABELAS
SELECT * FROM PARTICIPANTE
SELECT * FROM CURSO

INSERT INTO CURSO VALUES (6, 'PEDAGOGIA', 10.00)
DELETE FROM  CURSO WHERE CUR_CODCURSO = 6;
SELECT * FROM CURSO

DELETE FROM  PARTICIPANTE WHERE PAR_CPF = '04640203090';
SELECT * FROM PARTICIPANTE

DELETE FROM MATRICULA WHERE TUR_CODTURMA = 6;
SELECT * FROM MATRICULA

DELETE FROM INSTRUTOR WHERE INS_CPF = '03502197032';
SELECT * FROM INSTRUTOR 

DELETE FROM TURMA WHERE	TUR_CODTURMA = 2;
SELECT * FROM TURMA